### ISSUE TITLE
Set JNDI_FACTORY_PROPERTY also during test instance creation

### ISSUE THREAD

**Issue by abotos** [cdi-unit/cdi-unit#131]
Hi,

In `CdiRunner.createTest` the Weld container is invoked to create an instance of the test class. During this process the Weld container will initialize all other beans required for this test. The issue is that during this initialization of other beans, inside bean code one could make use of `new InitialContext()` to bind something to the context. Since at that moment of time there is no `java.naming.factory.initial` system property, this will result in an empty context, which will have no connection to the context that is used during the actual test method execution, since there `org.jglue.cdiunit.internal.naming.CdiUnitContextFactory` is being used to produce the `InitialContext`.

I suggest to wrap the call to `T t = container.instance().select(testClass).get()` in `CdiRunner.createTest` in a set/unset system property just like it is done in `CdiRunner.methodBlock` to wrap the original JUnit `Statement`.

BR,
Anghel

**Comment by ikysil** [comment]
This issue is specific to `CdiRunner` as other implementations do not create test instances.

**Comment by ikysil** [comment]
Closing in favor of #295 295
