### ISSUE TITLE
Any suggestions to speed up testing with CDI Unit?

### ISSUE THREAD

**Issue by csetera** [cdi-unit/cdi-unit#132]
We have a large number of CDI-unit based tests and we really love the framework.  The only thing that is difficult for us is the overall performance of the tests.  For any test class with a large number of test methods, CDI Unit (by design) creates the CDI environment with Weld before the test and then shuts it back down again.  This startup and shutdown is costly and we would love to be able to (somehow) only do it once per testcase class.  Obviously, there are potential issues with carryover between test methods that would need to be considered.

Any suggestions or thoughts?
Thanks,
Craig

**Comment by seanf** [comment]
Take a look at @chschroe74's pull request: https://github.com/BrynCooke/cdi-unit/pull/138

**Comment by seanf** [comment]
It's also possible https://github.com/BrynCooke/cdi-unit/pull/135/ could help a bit (if FastClasspathScanner really is fast).

**Comment by csetera** [comment]
#138 Looks interesting.  I will wait until that makes its way through.  I tried with #135 in place and didn't see any significant improvement.

**Comment by seanf** [comment]
On Mon., 2 Jul. 2018, 03:14 Craig Setera, <notifications@github.com> wrote:

> #138 <https://github.com/BrynCooke/cdi-unit/pull/138> Looks interesting.
> I will wait until that makes its way through.
>
No problem.

I tried with #135 <https://github.com/BrynCooke/cdi-unit/pull/135> in place
> and didn't see any significant improvement.
>
Okay.
But no worse, I hope?

**Comment by csetera** [comment]
Definitely no worse with the new classpath scanner.

**Comment by ikysil** [comment]
With the stock cdi-unit 4.1.0 we observe the following distribution of test suite (containing approx. 700 tests) execution time:

* total execution time: 11 minutes 30 seconds
* tests body execution time: 56 seconds
* classpath scanning: 6 minutes 52 seconds (412 seconds) 

Basically, half of the total execution time is spent scanning classpath.

See the screenshots from VisualVM below:

![Screenshot at 2020-04-13 10-19-17](https://user-images.githubusercontent.com/572398/79105140-57bc7880-7d70-11ea-9ce4-e8b6b02b7802.png)

![Screenshot at 2020-04-13 10-27-24](https://user-images.githubusercontent.com/572398/79105659-63f50580-7d71-11ea-85c6-63271a7c1c26.png)


Would it be possible to cache the result of the `WeldTestUrlDeployment#populateCdiClasspathSet`?
I can not imagine it changing during the execution of the test suite.

**Comment by ikysil** [comment]
Another point to consider is the usage of default `AutoCloseableExecutorService` by calls to `ClassGraph.scan()` which is used in `ClassGraphScanner` implementation. Every call to that method will create a fixed thread pool (8 thread on my machine) which is used only for that call and then is shut down. This approach creates and destroys 100K threads during the execution of the tests.

![Screenshot at 2020-04-13 10-31-17](https://user-images.githubusercontent.com/572398/79106212-57bd7800-7d72-11ea-80c0-746db43a789b.png)

**Comment by ikysil** [comment]
Check #158 for performance improvements relevant for projects with a large number of classes.

**Comment by vogelgsang-itestra** [comment]
In our project we experienced the same performance degradation as @ikysil . Upgrading from version 4.0.2 to version 4.1.0 doubled our test execution time. Most time is spent in `io.github.classgraph.ClassGraph.scan(ExecutorService, int)`
![image](https://user-images.githubusercontent.com/44408193/79335053-aeb57f80-7f21-11ea-8977-4d834edc2fa7.png)

**Comment by vogelgsang-itestra** [comment]
OMG I run our tests with the changes from the pull request #158 and it is so much faster!
Instead of 30 minutes it now takes only 3 minutes!
The performance profile for the test in my previous comment is much more balanced now
![image](https://user-images.githubusercontent.com/44408193/79345617-a107f600-7f31-11ea-90e1-3aa577a4844e.png)

I would very much appreciate if this pull request could be merged. Thanks @ikysil

**Comment by ikysil** [comment]
With the PR #158 merged into master for the upcoming release - are there any other suggestions, observations, and/or comments for performance improvements?

**Comment by ikysil** [comment]
Closing the issue - further proposals should be logged as new separate issues.

**Comment by dastrobu** [comment]
@ikysil do we see this in an 4.2.0 release soon?

**Comment by ikysil** [comment]
@dastrobu Yes, that's the idea.

**Comment by BrynCooke** [comment]
@ikysil Is there anything you need setting up to enable you to do the release? I was thinking that as the package name changed it could be an idea to swap to either a new org in maven central or better yet github packages....
