### ISSUE TITLE
No active contexts for scope type javax.enterprise.context.RequestScoped with @SupportJaxRs

### ISSUE THREAD

**Issue by cschabl** [cdi-unit/cdi-unit#133]
Using the instances injected by `@SupportJaxRs` results in the following Exception by Weld:

```
org.jboss.weld.contexts.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.enterprise.context.RequestScoped
```
To reproduce, add the following line to CDI-Unit test `TestJaxRs.testJaxRs()`:

```
Assert.assertNull(webService.request.getAttribute(("test")));
```

See [Stackoverflow question](https://stackoverflow.com/questions/26631093/no-active-contexts-for-scope-type-javax-enterprise-context-requestscoped-when-in) that might be related.

**Comment by ikysil** [comment]
Tests should be annotated with `@InRequestScope` in order to access methods of the `@RequestScoped` beans.

```java
	@Test
	@InRequestScope
	public void testRequestAttributeAccess() {
		Assert.assertNull(webService.request.getAttribute("test"));
	}
```
