### ISSUE TITLE
Problem with using ApplicationScoped beans in test cases

### ISSUE THREAD

**Issue by jpstrube** [cdi-unit/cdi-unit#137]
Hi,
we have a Wildfly Swarm application that we want to test. The problem is that ApplicationScoped beans seem to be new for every test case.

Here's a simple example:

    @ApplicationScoped
    public class TestBean {

        private AtomicInteger counter = new AtomicInteger();

        public int getCounter() {
            return counter.incrementAndGet();
        }
    }

And the tests:

    @RunWith(CdiRunner.class)
    public class CounterEndpointTest {

        @Inject
        private TestBean testBean;

        @Test
        public void testMethod1() {
            System.out.println(testBean.getCounter());
            System.out.println(testBean.getCounter());
        }

        @Test
        public void testMethod2() {
            System.out.println(testBean.getCounter());
            System.out.println(testBean.getCounter());
        }

        @Test
        public void testMethod3() {
            System.out.println(testBean.getCounter());
            System.out.println(testBean.getCounter());
        }
}

The output is `1,2,1,2,1,2` but I expected e.g. `1,2,3,4,5,6`.
Is my expectation wrong or do I miss something?

**Comment by seanf** [comment]
Hi Jan,

CDI-Unit does its best to achieve test isolation, so each method has its
own deployment, and thus its own bean instances. So testMethod3 will see 1,
2 whether you run it first, last, or by itself. That's kind of the way it
is.

If someone wants to contribute an optional mode for CDI-Unit which uses
less isolation, that could be useful for some users, both for your case and
for test performance.

**Comment by chschroe74** [comment]
I just created a pull request that solves this requirement. I added a new annotation "@IsolationLevel" which can be used to enable "PER_CLASS" isolation for certain test classes.
I did not yet add Javadoc to the annotation but could do so if the general approach is accepted.

**Comment by seanf** [comment]
Thanks @chschroe74! For future reference, the PR is here: https://github.com/BrynCooke/cdi-unit/pull/138

**Comment by ikysil** [comment]
Hi @jpstrube ,

The changes proposed in PR #138 were merged into the master branch.
Could you please confirm that this solves the issue for you?

**Comment by jpstrube** [comment]
Works now, thanks!

**Comment by ikysil** [comment]
Thank you.

I'm closing the ticket based on this feedback.
