### ISSUE TITLE
Provide a way (annotation) to exclude some classes from being automatically discovered by CDI-Unit

### ISSUE THREAD

**Issue by kalgon** [cdi-unit/cdi-unit#146]
On my project, we are integrating some non-CDI libraries by writing producers to make objects from those libraries accessible in our CDI-enabled code.

Our problem is that CDI-Unit tries to automatically discover some classes like in:

```java
@RunWith(CdiRunner.class)
@AdditionalClasses(MyTest.MyProducer.class)
public class MyTest {

    // Comes from a non-CDI library or a library with bean-discovery-mode="annotated"
    public static class MyService {

        public void hello() {
            System.out.println("hello");
        }
    }

    public static class MyProducer {

        @Produces
        public MyService myService() {
            return new MyService();
        }
    }

    @Inject
    private MyService myService;

    @Test
    public void test() {
        myService.hello();
    }
}
```

CDI-Unit will automatically discover and register the `MyService` class as a bean but the producer will produce exactly the same bean which makes the injection ambiguous (only for the tests but we want to include our producer in our tests).

So would it be possible to either declare `@VetoedClasses(MyService.class)` on the `MyTest` class or `@VetoedClass` on the `MyTest.myService` field (or any better named annotations)?

**Comment by ikysil** [comment]
Resolved with #169 which superceeds  #147
