### ISSUE TITLE
Cannot inject ContextController

### ISSUE THREAD

**Issue by jarekratajski** [cdi-unit/cdi-unit#151]
Problem when .gradle is in a symlink directory. 

Currenty  I am experiencing issues with cdi-unit. 
Final problem is that on some PCs it is impossible to Inject classes from cdi-unit - such as `ContextController`.
`WELD-001334: Unsatisfied dependencies for type ContextController with qualifiers @Default`

I've tracked the problem to this line:
https://github.com/BrynCooke/cdi-unit/blob/b5534a518a913eccacdeb267b7d39defead4a077/cdi-unit/src/main/java/org/jglue/cdiunit/internal/WeldTestUrlDeployment.java#L405

On the left side I have:
`file:/var/local/repos/.gradle/caches/modules-2/files-2.1/org.jglue.cdi-unit/cdi-unit/4.1.0/6b9da89f47ee7580dc138c617a12e555f2a1df77/cdi-unit-4.1.0.jar`
on the right:
`file:/home/jarek/.gradle/caches/modules-2/files-2.1/org.jglue.cdi-unit/cdi-unit/4.1.0/6b9da89f47ee7580dc138c617a12e555f2a1df77/cdi-unit-4.1.0.jar`

Because `/home/jarek/.gradle` is a symlink to `/var/local/repos/.gradle`

Problem is in classgraph component which does symlink resulution via `File.canonicalPath`.

EDIT:
There is a workaround - just forget about symlink and set GRADLE_USER_HOME or use -g param for gradle. (indices in gradle cahce fokders need to be recreated however).

**Comment by jarekratajski** [comment]
Probably the simplest solution would be to change getClassPathURL( c) method. 
If the URL is a File... then resolve to canonical one.

In fact I do see it as a bad idea that classgraph itself is doing such resolution.

**Comment by ikysil** [comment]
Dear @jarekratajski ,

The code which you are referencing was recently refactored and is not comparing the URL anymore.
See https://github.com/cdi-unit/cdi-unit/blob/251ee3490997f949284f765f6263d54368cd5a46/cdi-unit/src/main/java/org/jglue/cdiunit/internal/DefaultBeanArchiveScanner.java#L47.

Could you please check with cdi-unit built from the master branch?

**Comment by ikysil** [comment]
Resolution confirmed in #226.

The tests were failing until (obsolete) `org.jglue.github.cdiunit-archive` was properly renamed to `io.github.cdiunit-archive`.
