### ISSUE TITLE
Discover implementation of fields with interface type

### ISSUE THREAD

**Issue by serprime** [cdi-unit/cdi-unit#152]
When using cdi-unit the implementation classes are not discovered by default.

In our code base we have a guide line to use interfaces for all service classes.
All fields use the interface type.
This means, we need to manually add all required classes via annotations.
That is cumbersome and not useful.

Can we have a new feature, that cdi-unit finds and injects the implementations of interfaces used in field types?

Example:
```
class ServiceImpl {
  @Inject private OtherService otherService;
}

interface OtherService {}

class OtherServiceImpl implements OtherService {
}
```
So when testing `ServiceImpl` I expect `OtherServiceImpl` to be injected in `ServiceImpl.otherService`.

Sould this be enabled via annotation, or can this be the new default?
Did anybody else have this issue?

**Comment by ikysil** [comment]
Similar to #75.

Works as designed.
