### ISSUE TITLE
CdiRunner does not unbind the BeanManager in finally

### ISSUE THREAD

**Issue by teemueller** [cdi-unit/cdi-unit#187]
The class CdiRunner does not unbind the BeanManager in finally. This leads to test failures (NameAlreadyBoundException) if the test starts a NameServer itself in @BeforeClass.

The same applies to the cdi-unit extension for JUnit 5.

```
InitialContext initialContext = new InitialContext();
initialContext.bind("java:comp/BeanManager", container.getBeanManager());

try {
   defaultStatement.evaluate();

} finally {
   initialContext.unbind("java:comp/BeanManager");  // recommended fix
   initialContext.close();
   // ...
}
```

Are there any plans this will be fixed?

**Comment by ikysil** [comment]
Dear @teemueller,

Would you mind to create an example of the failing test scenario?

**Comment by ikysil** [comment]
Hi @teemueller 

Would it be possible to create a reproducer?
