### ISSUE TITLE
Version for Jakarta EE

### ISSUE THREAD

**Issue by martin-g** [cdi-unit/cdi-unit#195]
Please provide a version based on jakarta.** APIs.

Even a milestone/snapshot release would be very welcome!

**Comment by ikysil** [comment]
Yes, that's on the radar. No ETC, obviously.

**Comment by martin-g** [comment]
Depends on https://issues.apache.org/jira/browse/DELTASPIKE-1430

**Comment by ikysil** [comment]
- CDI 3.0 (not source-compatible with earlier versions)
- Weld 4.0.x

**Comment by martin-g** [comment]
Draft PR: https://github.com/cdi-unit/cdi-unit/pull/196

**Comment by ikysil** [comment]
Hi @martin-g ,

Thank you for the input, that looks interesting.
The change you are proposing is not backwards compatible with CDI specifications before 3.0.

Which begs a question: should we keep that compatibility?

**Comment by martin-g** [comment]
I am not well acquaint with CDI 😕  I am just trying to update Apache Wicket to Servlet API 5.x. `apache-cdi` uses cdi-unit for its unit tests.
AFAIK the only change in **all** new JEE specifications is the change from `javax.` to `jakarta.` package. But yes, this makes it binary incompatible with any older versions.
Are there are other new things in CDI 3.0 ?

**Comment by martin-g** [comment]
@jin-harmoney Any help to see a new release of cdi-unit is very welcome!

**Comment by jin-harmoney** [comment]
I tried, I got quite far actually, but deltaspike is not EE9/10 compatible. It's a huge pain. 

There are workarounds to use `classifier` in the pom:

```
<dependency>
	<groupId>org.apache.deltaspike.core</groupId>
	<artifactId>deltaspike-core-impl</artifactId>
	<classifier>jakarta</classifier>
	<scope>test</scope>
</dependency>
```

But there have been commits  on the deltaspike repo (https://github.com/rzo1/deltaspike/blob/master/deltaspike/parent/code/pom.xml#L165) that are not yet released related to this classifier.

**Comment by jin-harmoney** [comment]
@martin-g the discussion here is exploding: https://issues.apache.org/jira/browse/DELTASPIKE-1434?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=17643606#comment-17643606.. It doesn't look like we're going to have a jakarta-compatible version soon.

I was wondering if there is a heavy dependency on deltaspike in this project or if it could be replaced somehow? Or maybe excluded if it's not used?

**Comment by martin-g** [comment]
Yes, it is sad!

**Comment by jin-harmoney** [comment]
@martin-g deltaspike 2.0.0 is here! https://mvnrepository.com/artifact/org.apache.deltaspike.core/deltaspike-core-api

**Comment by martin-g** [comment]
That's nice !
@jin-harmoney Can you continue now with your [quest](https://github.com/cdi-unit/cdi-unit/issues/195#issuecomment-1302285643) ?

**Comment by jin-harmoney** [comment]
@martin-g yes! I'll keep you posted on our progress.

**Comment by jin-harmoney** [comment]
@ikysil we're working on a jakarte compatible version, but we were wondering if we should branch from `master` or from tag `4.1.0`, because there is quite some stuff on `master` that is not yet released.

**Comment by ikysil** [comment]
Hi @jin-harmoney 

Yeah, that's true - there are a lot of stuff on master which is not released yet.

Do you see the changes for Jakarta compatible version as straightforward?
Or some major refactorings are required?
New Maven modules needed?

**Comment by ikysil** [comment]
Let's keep your work on top of `master`.
I will prepare a new release with existing changes.

**Comment by ikysil** [comment]
Hello @jin-harmoney @har-cpol 

It's strange that Apache web site is not updated still - it lists `36th Release (1.9.4) (2020-06-12)` as the latest release.

Am I looking at wrong address?
https://deltaspike.apache.org/news.html

**Comment by ikysil** [comment]
A few observations on Deltaspike 2.0:
- it is neither source nor binary compatible with 1.x series
- it requires Java 11

**Comment by martin-g** [comment]
That's fine!
Almost all projects moved to Java 17+ while doing the migration to jakarta.**
Java 8 is way too old!

**Comment by ikysil** [comment]
Sure, that's fine for the future MAJOR release of cdi-unit.

I'm looking at this from the next 4.x release perspective where Java 8 compatibility is still a thing.

**Comment by martin-g** [comment]
Do you mean that you want to release cdi-unit for jakarta.** in a minor version ?

**Comment by ikysil** [comment]
JakartaEE is one of the features for the next MAJOR release.

Other items (I am aware of) are:
- Artifact coordinates - jglue.org has expired a long time ago
- JUnit5 support

**Comment by ikysil** [comment]
JakartaEE is one of the features for the next MAJOR release.

Other items (I am aware of) are:
- Artifact coordinates - jglue.org has expired a long time ago - see #159 
- JUnit5 support - see #103

**Comment by ikysil** [comment]
PR #230 has been merged into the master.

I'm closing this issue and proceeding with a EA release.

**Comment by ikysil** [comment]
Version 5.0.0-EA1 has been published.
[`pkg:maven/io.github.cdi-unit/cdi-unit@5.0.0-EA1`](https://central.sonatype.com/artifact/io.github.cdi-unit/cdi-unit/5.0.0-EA1)

Please check and report any issues!
