### ISSUE TITLE
Case sensitivity in URL comparison

### ISSUE THREAD

**Issue by antalk** [cdi-unit/cdi-unit#197]
The class WeldTestUrlDeployment  checks for a class being CDI against 'cdiClasspathEntries' 

However this is done in a case sensitive manner and we have issues on our Jenkins builds that resolves in cdiClasspathEntries  having different case than the class being analyzed.

For instance:

A CDI bean is in our CDI classpath entry:

**file:/D:/dat/maven/nl/organization/commons/commons-application/1.0.36/commons-application-1.0.36.jar**

BUT; the 'isCdiClass' method returns:

**file:/d:/dat/maven/nl/organization/commons/commons-application/1.0.36/commons-application-1.0.36.jar**

and does not resolve it as being a CDI class . Because of the 'D'  drive letter mismatch.

A better cdi (URL)  check would be this:

```
private boolean isCdiClass(Class<?> c) {
		URL location = getClasspathURL(c);
		if (location != null ) {
			
			Optional<String> match = cdiClasspathEntries.stream().map(URL::toString).filter(s -> s.equalsIgnoreCase(location.toString())).findFirst();
			return match.isPresent();
		}
		return false;
		
	}
```

**Comment by antalk** [comment]
oops. im sorry is the same as #150

**Comment by ikysil** [comment]
Hi @antalk 

Could you please check with cdi-unit built from the master branch?

It looks like I should really accelerate the next release ;)

**Comment by antalk** [comment]
Yes a new release would be a good idea.

**Comment by ikysil** [comment]
Resolution confirmed in https://github.com/cdi-unit/cdi-unit/issues/151 and https://github.com/cdi-unit/cdi-unit/pull/226.

The tests were failing until (obsolete) org.jglue.github.cdiunit-archive was properly renamed to io.github.cdiunit-archive.
