### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by krisgerhard** [cdi-unit/cdi-unit#203]
Last release to Maven repository was done over 4 years ago.
There are many improvements in this repository, is there any plan to release a new version?

**Comment by ikysil** [comment]
Hi @krisgerhard 

Thank you for your interest.

Yes, I may plan another release with the changes which are already accumulated here.

I am not sure about adding support for anything beyond Java EE 7 though as [Apache DeltaSpike](https://deltaspike.apache.org/) is [struggling](https://issues.apache.org/jira/browse/DELTASPIKE-1434)  with that update as well and pulling DeltaSpike out of CDI-Unit is equal to full rewrite.

Is there any interest in using CDI-Unit for testing in Jakarta EE ?

**Comment by tomlux** [comment]
we would like to use CDU-unit for testing in Jakarta EE

**Comment by aschoerk** [comment]
Hello,
in ioc-unit I only use only a small part of deltaspike which was easy to port. I think it might be similar with cdi-unit.
See: https://github.com/1and1/ioc-unit/tree/jakarta/weld-starter/weld-starter-base/src/main/java

**Comment by antalk** [comment]
One more like from me to support jakarta namespace.

**Comment by ikysil** [comment]
FYI - I'm updating current `master` for a new release.

**Comment by ErhardSiegl** [comment]
What are the plans for this release? Will there be Jakarta 10 Support? Is there a approximate time plan for Jakarta 10 Support? (Background: We have a project using CDI-Unit that will migrate to Jakarta10)

**Comment by ikysil** [comment]
See release announcement at #223
