### ISSUE TITLE
Organization ownership continuity

### ISSUE THREAD

**Issue by ikysil** [cdi-unit/cdi-unit#211]
Hi @BrynCooke 

It looks like nobody except you has permissions to properly maintain the organization.

Would you mind sharing this load/privilege with other people?
I would suggest following the recommendations from GitHub and having at least 2 persons with organization owner roles.

Check https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/maintaining-ownership-continuity-for-your-organization for the relevant docs.

I would like to step up to this role and perform further maintenance of the project.

**Comment by BrynCooke** [comment]
@ikysil I've sent you an invite!

**Comment by ikysil** [comment]
Do you still have valid account at Sonatype? There were significant changes since March this year.

**Comment by BrynCooke** [comment]
Hmm I just tried to log on and things seemed bust. I'll have to try again tomorrow.

**Comment by ikysil** [comment]
Steps to recover the publishing setup (as of 2024-06-01):

- go to [OSSRH Account Management Portal](https://account.oss.sonatype.org/realms/central-ossrh/account/)
- reset password using `Forgot Password?` functionality
- login to the [OSS Nexus](https://oss.sonatype.org) using user name & password
- go to Profile -> User Token and generate new access token
- put those in `setting.xml` for server IDs `sonatype-nexus-snapshot` and `sonatype-nexus-staging`

I've managed to deploy the RC release to the staging repository and pass all validation rules.

**Comment by BrynCooke** [comment]
Great, this worked. Let me know if there is anything that you need from me to do.

**Comment by ikysil** [comment]
Works fine for me so far.
