### ISSUE TITLE
jakarta.ee support for EE 10 / servlet api 6.0.0

### ISSUE THREAD

**Issue by har-cpol** [cdi-unit/cdi-unit#249]
Hello,

On the current 5.x release, the version of jakarta.jakartaee-web-api version is set to 9.0.0 (~ servlet 5.0 )

This is not compatible with projects using jakarta.jakartaee-web-api 10.0.0 (~ servlet 6.0 )
There are incompatible changes in the servlet api.

I managed to make changes to support 10.0.0 that work for my case, but those changes will not be working with 9.0.0.

Are there any plans to handle support for both versions ? 
Or provide support for 10.0.0. That would solve my case but maybe causes issues for others.

Some elaboration of the incompatible changes that cause issues
Version 10.0.0 vs 9.0.0
(1) removes class jakarta.servlet.http.HttpSessionContext, and removes method getSessionContext() from HttpSession class
(2) adds class jakarta.servlet.ServletConnection, and adds getServletConnection() to ServletRequest

So to make the code work with version 10.0.0
(1)  requires to remove following method from MockHttpSessionImpl:
`
    public synchronized HttpSessionContext getSessionContext() {
        return new MockSessionContext();
    }
`
But that change makes the class incompatible with interface definition of HttpSession in 9.0.0

(2) requires to add following method to MockHttpServletRequestImpl:
`    @Override
    public ServletConnection getServletConnection() {
         return null; // or something useful
    }
`
But these changes will not work on 9.0.0 since ServletConnection return type is an unknown class there.

So I don't see an easy way to support both api versions in a single code base.

I'd propose to upgrade the dependency to 10.0.0. 
What do you think ?

**Comment by ikysil** [comment]
Hi @har-cpol 

Would you mind testing against PR #250 ?

**Comment by ikysil** [comment]
Hi @har-cpol 

TY, I will look into it ASAP.

**Comment by ikysil** [comment]
Hi @har-cpol 

Version [pkg:maven/io.github.cdi-unit/cdi-unit@5.0.0-EA2](https://central.sonatype.com/namespace/io.github.cdi-unit) has been published.

Please check with it.
