### ISSUE TITLE
JNDI InitialContextFactory (or Builder) should be available over the lifecycle of a test instance.

### ISSUE THREAD

**Issue by ikysil** [cdi-unit/cdi-unit#295]
JNDI InitialContextFactory (or Builder) should be available over the lifecycle of a test instance.

Rationale:
- the lifespan of the test instance defines the lifespan of the `@ApplicationScope` under test.

Expected behavior:
- the system property `java.naming.factory.initial` is set on _first_ CDI container initialization;
- the system property `java.naming.factory.initial` is reset on _last_ CDI container shutdown;
- each created CDI container is bound to the `java:comp/BeanManager` on initialization and unbound on shutdown;

This issue supersedes #131.

TODO:
- [ ] JUnit 4 Runner
- [ ] JUnit 4 Rule
- [ ] TestNG Runner
- [ ] TestNG Listener
- [ ] JUnit 5 Top-level test
- [ ] JUnit 5 Nested test

**Comment by ikysil** [comment]
Consider using `javax.naming.spi.NamingManager#setInitialContextFactoryBuilder` instead of property as it can not be overridden.

**Comment by tomlux** [comment]
I'm trying to connect to an ldap-server in my testmethod, but the ldap-"DirContext" is never correctly loaded.
Does it need a special comfig for this?

`
 @Test
  public void testLdap() {
       Hashtable<String, String> environment = new Hashtable<String, String>();
       environment.put(Context.INITIAL_CONTEXT_FACTORY, "com.sun.jndi.ldap.LdapCtxFactory");
       environment.put(Context.PROVIDER_URL, "ldap://localhost:10389");
       environment.put(Context.SECURITY_AUTHENTICATION, "simple");
       environment.put(Context.SECURITY_PRINCIPAL, "uid=admin,ou=system");
       environment.put(Context.SECURITY_CREDENTIALS, "secret");
       DirContext adminContext = new InitialDirContext(environment);
 }
`

The "DirContext" is created, but the ldap-connection is not correctly created.
The 'LdapCtxFactory" seems to be ignored in my test...
_(running with cdi-unit-junit4 with latest v5.0.0 source)_

**Comment by ikysil** [comment]
@tomlux please create a separate issue.
