### ISSUE TITLE
Improvement: Make Annotations inheritable

### ISSUE THREAD

**Issue by PeterProbst** [cdi-unit/cdi-unit#66]
Hello Bryn,
please can you make following Annotations inheritable:
AdditionalClasses, AdditionalClasspaths, AdditionalPackages.
This removes redundancy in test inheritance.
Thank you, Peter

**Comment by BrynCooke** [comment]
I will do this in the next version. However you should find that they are already inheritable (even without the annotation). In fact the entire transitive closure of classes in the test is examined for those annotations, so you can factor out bits of test functionality in to utility classes already.

**Comment by BrynCooke** [comment]
Check out the SupportsDeltaspike* annotations. This is a simple example of where the closure of test classes are discovered.

**Comment by ikysil** [comment]
Implemented as part of #59 - check `SupportDeltaspikeJpa` and `SupportDeltaspikeData` annotations and their usage in the `TestDeltaspikeTransactions` test case.
