### ISSUE TITLE
Incompatible with embedded Tomcat?

### ISSUE THREAD

**Issue by gcobr** [cdi-unit/cdi-unit#68]
I recently added some tests to my project that use CdiRunner. They worked wonderfully, and I loved this library. 

However, I had other tests that were starting an embedded Tomcat, which now fail to initialize.

Apparently, a listener related to CDI Unit gets involved in Tomcat's startup even when my test cases have no reference whatsoever to CdiRunner.

It seems that the sheer presence of CDI Unit in the classpath makes this happen.

I run my tests on Eclipse, with a regular JUnit launch configuration. Therefore, I have little control over the classpath.

My classpath is, in fact, determined by Gradle (a build/dependency manager similar to Maven), which is nicely integrated into Eclipse by a plugin. I configure my test dependencies in a build.gradle file, and the plugin adds them to the project's classpath in Eclipse. Hence, when I run a JUnit test, Eclipse creates a launch configuration with the same classpath as the project, which, at that point, will contain CDI Unit.

```
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type WeldListener with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject @ApplicationScoped private org.jglue.cdiunit.ContextController.listener
  at org.jglue.cdiunit.ContextController.listener(ContextController.java:0)
```

I wish there was a way to solve this without removing CDI Unit from the classpath.

**Comment by BrynCooke** [comment]
Please give 3.1.3 a go. This may work now if we are lucky.

**Comment by jansohn** [comment]
For me upgrading to version 3.1.3 fixed this error. Thanks!

**Comment by ikysil** [comment]
Dear @gcobr ,

Please comment if upgrading to the later version of cdi-unit fixed your issue?

**Comment by ikysil** [comment]
Closing as feedback was not provided for a long time while multiple new releases were produced.
