### ISSUE TITLE
Support for CDI injection in entity listeners

### ISSUE THREAD

**Issue by robbertbrak** [cdi-unit/cdi-unit#73]
In JPA 2.1, entity listeners should now support CDI injection. See, for example, https://blogs.oracle.com/theaquarium/entry/better_cdi_alignment_in_jpa.

However, I can't seem to get it to work in my unittests with cdi-unit. Is this not supported? If not, do you have any plans to add support?

**Comment by BrynCooke** [comment]
I'm not entirely sure how this would work. cdi-unit doesn't really integrate with other frameworks as such, it's more suited to mocking. How are you using JPA inside your unit tests? and where does CDI unit fit in?

**Comment by ikysil** [comment]
Closing as not relevant - according to [3.5.1. Entity Listeners](https://jakarta.ee/specifications/persistence/3.1/jakarta-persistence-spec-3.1#entity-listeners)

> The persistence provider is responsible for using the CDI SPI to create instances of the entity listener class; to perform injection upon such instances; to invoke their PostConstruct and PreDestroy methods, if any; and to dispose of the entity listener instances.
