### ISSUE TITLE
Injection of @Produces always requires @AdditionalClasses

### ISSUE THREAD

**Issue by baztian** [cdi-unit/cdi-unit#75]
In the user guide you write

> CDI-Unit will try to discover what classes should be available to the CDI environment automatically, but sometimes this is not possible.

Can you please specify this in greater detail?

I didn't manage to inject any dependency that is provided via @Produces other than dependencies that are part of the project I'm writing tests for. For all other cases I always have to use @AdditionalClasses which is annoying. Even for classes from the jdk standard library like java.util.loggin.Logger or String @AdditionalClasses is required :(

I have this in my src/main/java:

``` java
import java.util.logging.Logger;
public class LoggerProducer {

    @Produces
    Logger createLogger(InjectionPoint ip) {
        return Logger.getLogger(ip.getMember().getDeclaringClass().getName());
    }
}
```

And this is my unit test in src/test/java:

``` java
@RunWith (CdiRunner.class)
// @AdditionalClasses (LoggerProducer.class)
public class CdiUnitProducerInjectionTest {
    @Inject
    private Logger logger;
    @Test
    public void testApp() {
        logger.log(Level.INFO, "Testmessage.");
    }
}
```

I'm getting
`org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type Logger with qualifiers @Default`.

It makes no difference if I add a beans.xml to src/main/resources and/or src/test/resources. Do I really have to use the @AdditionalClasses annotation?

Without CDI-Unit I can easily run

``` java
public static void main(String[] args) {
    Weld weld = new Weld();
    WeldContainer container = weld.initialize();
    Logger logger = container.instance().select(Logger.class).get();
    logger.log(Level.INFO, "Testmessage.");
    weld.shutdown();
}
```

without any issues.

**Comment by BrynCooke** [comment]
There are several annotations available 
http://jglue.org/cdi-unit-user-guide/#controllingEnvironment
AdditionaClasspath will give you functionality closest to what you desire.
The reason that annotations are used are to prevent the entire CDI environment for you app being set up for every test.

**Comment by ikysil** [comment]
Works as designed.
