### ISSUE TITLE
JVM and JDK settings

### ISSUE THREAD

**Issue by jeusdi** [cdi-unit/cdi-unit#76]
I'm using querydsl. It compiles new classes at runtime in order to project some result classes.
So, I'm testing my tests using cdi-runner, and when I perform the next sentence:

```
List<String> newKeys = from(lqmv, fua.getMetainfos()).list(lqmv.key);
```

It lasts 2 or 3 seconds. When I perform it in a container, it's almost snappy.

I've look on where's the problem. I guess about JDK & JVM cdi-runner settings. Could it be possible?

**Comment by ikysil** [comment]
Dear @jeusdi ,

Could you please create a repository with the test code reproducing the issue?

Thank you in advance

**Comment by ikysil** [comment]
It's impossible to investigate without a good reproducer.

@jeusdi feel free to create one and reopen this issue.
