### ISSUE TITLE
Use @Singleton for test class scope

### ISSUE THREAD

**Issue by kdubb** [cdi-unit/cdi-unit#80]
Currently `@ApplicationScoped` is assigned to the test class.  This precludes the use of JUnit rules because Weld does not allow public members in classes that have normal scope.

Switching to `@Singleton`, which is a pseudo scope, doesn't have the same limitations and would allow the use of rules.

**Comment by ikysil** [comment]
Dear @kdubb ,

While you are right that using a public **field** is not possible, it is well possible to use JUnit rules in the tests controlled by CdiUnitRunner.

You need to create a public method annotated with `@Rule` which returns the rule instance.

But anyway, feel free to create a pull request.

**Comment by ikysil** [comment]
The following test is passing:

```java
@RunWith(CdiRunner.class)
public class TestJUnitRule {

	private final TestName testName = new TestName();

	@Rule
	public TestName getTestName() {
		return testName;
	}

	@Test
	public void testName() {
		Assert.assertNotNull("test name is expected", getTestName().getMethodName());
	}

}
```

**Comment by ikysil** [comment]
Similar issue #83
