### ISSUE TITLE
cdi-unit fails with maven failsafe plgin

### ISSUE THREAD

**Issue by tkruse** [cdi-unit/cdi-unit#87]
Hi, as reported here in the comments
https://issues.jboss.org/browse/WELD-2054

cdi-unit fails to find a bean-archive when running maven failsafe-plugin without the beans.xml.
To reproduce, clone https://github.com/tkruse/weld-implicit-archive
and run mvn clean verify.

**Comment by ikysil** [comment]
Hi @tkruse 

The example project is not available anymore under the URL above.
Would you mind to add it here?

**Comment by tkruse** [comment]
8 years later, I have zero context, and don't think I have any copy of that project left anywhere, feel free to close this issue
