### ISSUE TITLE
Add support for "@Resource" injection. [CDI Extension included]

### ISSUE THREAD

**Issue by exabrial** [cdi-unit/cdi-unit#90]
Currently cdi-unit does not support `@Resource` injection. Here is a simple CDI Extension that covers a huge amount of use cases:

```
public class AtResourceInjectionCDIExtension implements Extension {
   <T> void processAnnotatedType(@Observes ProcessAnnotatedType<T> pat) {
      Set<AnnotatedField<? super T>> fields = pat.getAnnotatedType().getFields();
      for (AnnotatedField<? super T> field : fields) {
         if (shouldInjectionAnnotationBeAddedToField(field)) {
            AnnotatedType<T> at = pat.getAnnotatedType();
            AnnotatedTypeBuilder<T> builder = new AnnotatedTypeBuilder<T>().readFromType(at);
            Inject injectAnnotation = AnnotationInstanceProvider.of(Inject.class);
            builder.addToField(field, injectAnnotation);
            pat.setAnnotatedType(builder.create());
         }
      }
   }

   private <X> boolean shouldInjectionAnnotationBeAddedToField(AnnotatedField<? super X> field) {
      return !field.isAnnotationPresent(Inject.class) && field.isAnnotationPresent(Resource.class);
   }
}
```

**Comment by KirillGrishin** [comment]
How would I use this one if it is not in the library?

**Comment by seanf** [comment]
@KirillGrishin I think you just need to add this to your test class:

    @AdditionalClasses(AtResourceInjectionCDIExtension.class)

**Comment by gitdode** [comment]
Great, just what I was looking for and works fine - thanks!

**Comment by KirillGrishin** [comment]
@seanf Thanks, it looks to be processing it now! May I ask another question? How do I inject String resources for tests?

```Java
@Resource(name = "PROPERTIES_PATH")
private String propertiesFilePath;
```

**Comment by exabrial** [comment]
I would recommend Sabot for that: https://tomitribe.io/projects/sabot

**Comment by aschoerk** [comment]
Hello,
at our company we faced similar problems and solved them using cdi-unit together with an additional Modul that extended the EjbExtension class and added some classes which help with transactionmanagement and queue-simulation. Perhaps you would like to take a look: [ejb-cdi-unit](https://github.com/1and1/ejb-cdi-unit)
