### ISSUE TITLE
java.io.IOException: Permission denied - when a bean try to access to the filesytem

### ISSUE THREAD

**Issue by edesdan** [cdi-unit/cdi-unit#95]
Hi,
I'm struggle with this at the moment. Maybe someone can help me. Basically I have this test class configured to run with cdiRunner:

```
@RunWith(CdiRunner.class)
@AdditionalClasses({LoggerProducer.class, SfgClientProducer.class, EventAdapter.class, ConfigProvider.class})
public class EventProcessorTest {


    @Inject
    EventProcessor eventProcessor;


    @Test
    public void testInjection(){

        assertTrue(eventProcessor != null);
    }

}
```

The Injected EventProcessor uses another bean that needs to create a file on FileSystem during init phase:

```
@ApplicationScoped
public class ConfigProvider {

    @Inject
    transient Logger logger;

    private GhibliSfgAgentConfig config;


    @PostConstruct
    void init() {
        try {
            logger.info("initializing configuration ...");

            PropertiesStore propertiesStore = new ConfigPropertiesStoreBuilder().build();

        } catch (PropertiesBeanProviderException e) {
            throw new GhibliSfgAgentRuntimeException("cannot initialize configuration", e);
        }
    }

    public GhibliSfgAgentConfig getConfig() {
        return config;
    }
}
```

The problem is that when I try to do that I'm getting this exception: 

`87 more
Caused by: java.io.IOException: Permission denied
    at java.io.UnixFileSystem.createFileExclusively(Native Method)
    at java.io.File.createNewFile(File.java:1006)`

I tried to also mock the configProvider class but without success.

**Comment by JSplain** [comment]
What was the fix?   jimsplain@hotmail.com

**Comment by ikysil** [comment]
It looks like the original issue (file system permissions) has nothing to do with either CDI, Weld, or CDI Unit.

Closing as WONT FIX.
